### ISSUE TITLE
Unable to automatically verify otp code

### ISSUE THREAD

**Issue by xstreamcl** [SendOTP/SendOTPAndroid#12]
I have just upgraded from 2.5 to 2.7 and now it is unable to automatically read SMS to verify otp code. I have checked through the code and found responsible code commented out. 

[
IntentFilter filter = new IntentFilter();
filter.addAction("android.provider.Telephony.SMS_RECEIVED");
filter.addAction(android.telephony.TelephonyManager.ACTION_PHONE_STATE_CHANGED);
mContext.registerReceiver(setUpReceiver(), filter);
]

Please help me to proceed further.

**Comment by rakshitsoni02** [comment]
We have removed auto verification due to technical issues we can help you in that by proving code snippet kindly share your email id.

**Comment by xstreamcl** [comment]
Hi Rakshit,

So sorry to hear that. The primary reason I choose to use your sdk is
because of auto SMS read functionality. I would like to know the
complications that you have faced and the the code snippet.

Thanks

**Comment by rakshitsoni02** [comment]
May i know your mailing address our support executive will get in touch with you soon .

**Comment by xstreamcl** [comment]
Email -  yogeshchoudhary.cl@gmail.com

**Comment by sunilSubramannian** [comment]
Please forward the auto sms read functionality code.....
Email: sunil@clicksbazaar.com

**Comment by rahularyanab** [comment]
Please forward the auto sms read functionality code.....
Email: rahul.aryanab@gmail.com
