### ISSUE TITLE
app getting destroyed

### ISSUE THREAD

**Issue by sunilSubramannian** [SendOTP/SendOTPAndroid#14]
When other app is called like the message app....The otp activity is getting destroyed....due to which the user may not be able to go to see the otp code in the message app.

**Comment by rakshitsoni02** [comment]
Please provide more information including your logs trace.

**Comment by sunilSubramannian** [comment]
Sorry for the delay, I just checked by implementing the android lifecycle callbackes from there I came to know that the app is getting closed while user navigates to the message app or recieves a call
