### ISSUE TITLE
Network on main thread exception (2.8)

### ISSUE THREAD

**Issue by xstreamcl** [SendOTP/SendOTPAndroid#15]
android.os.NetworkOnMainThreadException
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1287)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:688)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okio.Okio$2.read(Okio.java:139)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.internal.Util.skipAll(Util.java:178)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.internal.Util.discard(Util.java:160)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:397)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okio.RealBufferedSource.close(RealBufferedSource.java:396)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.internal.Util.closeQuietly(Util.java:90)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.ResponseBody.bytes(ResponseBody.java:85)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at okhttp3.ResponseBody.string(ResponseBody.java:109)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at com.msg91.sendotp.library.internal.VerificationMethod$5.run(VerificationMethod.java:239)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:746)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
11-25 01:28:05.579  9838  9838 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by xstreamcl** [comment]
@SendOTP @rakshitsoni02 -  Guys, are we doing anything around this? It is not able to let us go live.

**Comment by koolkvd** [comment]
I am myself just going to use their REST API and post to get and verify otp... Until they sort this issue out, i advise you to do the same. Do the posting part inside a non ui thread :)

**Comment by koolkvd** [comment]
Do let me know how things go... How good the service is ...  kushan.dave1@gmail.com

**Comment by rakshitsoni02** [comment]
@xstreamcl @koolkvd  Our executive will be in touch with you soon.

**Comment by rakshitsoni02** [comment]
@xstreamcl @koolkvd please update to 2.9

**Comment by xstreamcl** [comment]
Updated... Everything seems fine as of now.. Will let you know if something breaks.. Thanks
