### ISSUE TITLE
OTP initiation failed

### ISSUE THREAD

**Issue by iammrj** [SendOTP/SendOTPAndroid#16]
Hii, I've integrated the SDK and followed the all steps as shown here. But every time i click on my GetOTP button it is calling the method onInitiationFailed() method. when print stacktrace of exception it has shown me the error message 

> "{"status":"error","response":{"code":"Insufficient Balance in OTP Route"}}"

please tell me **how to use demo sendOTP service** before purchase.

**Comment by rakshitsoni02** [comment]
@iammrj forwarded your issue to our support team.
