### ISSUE TITLE
Verification initialization failed: Bad Request

### ISSUE THREAD

**Issue by axay** [SendOTP/SendOTPAndroid#4]
Any way to debug this error ?

**Comment by rakshitsoni02** [comment]
please check your secret key for more info look this link
http://help.msg91.com/article/181-how-to-generate-key-hash-for-android

**Comment by shubhang-malviya** [comment]
I am also facing the same issue. I have also checked my secret key in the panel.

**Comment by tanviag** [comment]
I am also facing the same issue. I have checked the secret key in the panel also.

**Comment by tanviag** [comment]
I have fixed the above issue but now "OTP has been Sent successfully" but it is not received on phone.
Please tell what could be the problem I am facing.
