### ISSUE TITLE
Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference

### ISSUE THREAD

**Issue by vipulasri** [SendOTP/SendOTPAndroid#5]
> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference
>        at com.msg91.sendotp.library.internal.VerificationMethod$1.onPostExecute(SourceFile:73)
>        at com.msg91.sendotp.library.internal.VerificationMethod$1.onPostExecute(SourceFile:61)
>        at android.os.AsyncTask.finish(AsyncTask.java:632)
>        at android.os.AsyncTask.access$600(AsyncTask.java:177)
>        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:135)
>        at android.app.ActivityThread.main(ActivityThread.java:5312)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:372)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

I am getting this error in production app on some devices.

Devices : 

1. Model Number : XT1068 
    Brand : Motorola 
    OS: Android 5.0.2

2. Model Number : aqua_lifeiii 
    Brand : Intex
    OS: Android 5.1

**Comment by rakshitsoni02** [comment]
Thats weird, thanks for reporting I will fix it soon.

**Comment by xstream365** [comment]
I am facing similar problem. Any updates here?

**Comment by rakshitsoni02** [comment]
please check and let me know.
